### ISSUE TITLE
Explain better the role of this widget

### ISSUE THREAD

**Issue by commonsguy** [rno/Android-ScrollBarPanel#1]
I am sure that this is a very nice widget. However, at the moment, your sole description is that it is "like Path", which will only make sense to people who use that app. Not everybody uses Path. For example, I do not use Path. Hence, I have no idea what your widget does that is not already handled by `SectionIndexer` in the SDK.

IMHO, adding a few sentences to the README explaining the widget's behavior and its use cases will make it easier for developers to determine whether or not your widget meets their particular needs.

**Comment by JakeWharton** [comment]
Providing a demo app on the Play Store (or at the very least as a download) would be nice as well so someone can get a quick feel for the functionality. I too have never used Path and am curious about what the widget truly does differently than `SectionIndexer`.

**Comment by DarkUD** [comment]
I dont use path either. I make a quick research and find a path 2 finance. But I m pretty sure it s not that... They are right, you better explain what your widget will really do in details so people will want to help you.

**Comment by florianmski** [comment]
This is a video of the Path app http://vimeo.com/32856179
I think this lib wants to recreate the little clock next to the scrollbar at 0:08
Last time I've checked, this functionnality wasn't in the android app.

**Comment by rno** [comment]
Thanks for your remark.

I have updated the github project description and the description inside the README. I have also published the sample in the Play Store https://play.google.com/store/apps/details?id=com.dafruits.android.samples&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5kYWZydWl0cy5hbmRyb2lkLnNhbXBsZXMiXQ..

Hope it's better now.
